### ISSUE TITLE
Unable to login and connect

### ISSUE THREAD

**Issue by GabrieleCicconetti** [tigase/tigase-xmpp-server-docker#7]
I'm trying to build a simple xmpp server just to learn. After the setup i'm not able to login in localhost:8080/admin.
This is the config.tdsl
```
admins = [
    'admin@009ec9fa7e7b'
]
'config-type' = 'default'
debug = [ 'server' ]
'default-virtual-host' = '009ec9fa7e7b'
dataSource () {
    default () {
        uri = 'jdbc:derby:tigasedb;create=true'
    }
}
http () {
    setup () {
        'admin-password' = 'admin'
        'admin-user' = 'admin'
    }
}
pubsub () {
    trusted = [ 'http@{clusterNode}' ]
}
```

I set all the username and passwords to admin:admin but i cannot login.
This is the docker-compose i used to start the server
```
version: '3.3'
services:
  xmpp:
    image: tigase/tigase-xmpp-server:nightly-8.3-2022-10-26
    ports:
      - "5222:5222"
      - "5280:5280"
      - "5290:5290"
      - "8080:8080"
    environment:
      DB_ROOT_USER: root
      DB_ROOT_PASS: root-password
      ADMIN_JID: admin
      ADMIN_PASSWORD: admin
    volumes:
      - ./etc/:/home/tigase/tigase-server/etc/
      - ./certs/:/home/tigase/tigase-server/certs/
      - ./data/:/home/tigase/tigase-server/data/
      - ./logs/:/home/tigase/tigase-server/logs/
   ```

The second problem is that i'm trying to use this server with angular and ngx-chat but i don't understand which is the url to connect to the webSocket. For localhost i'm using ws://localhost:5290 but it doesn't work. 

How can i find the correct socket url?

Thank you in advance for the help.
